Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,40 +19,27 @@ strategy:
   maxParallel: 3
 
 steps:
-- task: UsePythonVersion@0
+- task: Bash@3
   inputs:
-    versionSpec: '$(PYTHON_VERSION)'
-    architecture: 'x64'
-
-- task: PythonScript@0
-  displayName: 'Export project path'
-  inputs:
-    scriptSource: 'inline'
-    script: |
-      """Search all subdirectories for `manage.py`."""
-      from glob import iglob
-      from os import path
-      # Python >= 3.5
-      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
-      if not manage_py:
-          raise SystemExit('Could not find a Django project')
-      project_location = path.dirname(path.abspath(manage_py))
-      print('Found Django project in', project_location)
-      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))
-
-- script: |
-    python -m pip install --upgrade pip setuptools wheel
-    pip install -r requirements.txt
-    pip install unittest-xml-reporting
-  displayName: 'Install prerequisites'
-
-- script: |
-    pushd '$(projectRoot)'
-    python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
-  displayName: 'Run tests'
-
-- task: PublishTestResults@2
-  inputs:
-    testResultsFiles: "**/TEST-*.xml"
-    testRunTitle: 'Python $(PYTHON_VERSION)'
-  condition: succeededOrFailed()
+   targetType: 'inline'
+   script: |
+    i=0
+    end=30
+        while [ $i -lt $end ]
+        do
+            i=$(( $i + 1 ))
+            curl --location --request POST 'https://qa.armorcode.ai/client/buildvalidation' --header 'Content-Type: application/json' --header 'Authorization: Bearer $(ARMORCODE_TOKEN)'  -d '{ "env": "Production", "product": "212331980", "subProduct": "327627", "buildTool":"AZURE_PIPELINE", "buildNumber": "$(Build.BuildId)","current":"'$i'" , "end":"'$end'"}' > result.json
+            status=$(jq -r '.status' result.json)
+            if [ $status = "HOLD" ]
+            then
+                echo "Armorcode SLA failed."
+                sleep 10
+                echo "Sleeping 10 seconds before trying again. You can temporarily release the build from Armorcode console"
+            elif [ $status = "FAILED" ]
+            then
+                echo "Exiting with error code 1"
+                exit 1
+            else
+                break
+            fi           
+        done
